version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chat-app
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: chat-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-server
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/chat-app?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://localhost:3000
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      NEXT_PUBLIC_SERVER_URL: http://localhost:5000
    depends_on:
      - server

volumes:
  mongodb_data:
  redis_data: